### ISSUE TITLE
I get an error when installing

### ISSUE THREAD

**Issue by OPEN1004MIND** [Benature/obsidian-metadata-hider#1]
I get an error when installing from the community plugin.
...  when installing from the BRAT plugin too.
Is there a update version issue? 
Please check ~

**Comment by Benature** [comment]
sorry for the issue, the plugin should be able to be installed now.

**Comment by Benature** [comment]
> I'm hoping to fix the part where the last added YAML is visible soon.

Hi @OPEN1004MIND , v0.1.0 remove the workaround that always shows the last property, now the plugin will show all properties (including the newly added one) when the property table is focused (e.g. click, input).
