### ISSUE TITLE
[FR] Provide option to not hide empty properties

### ISSUE THREAD

**Issue by a13ph** [Benature/obsidian-metadata-hider#5]
As a user, I would like to always hide particular properties without hiding all the empty ones.
Maybe add a palette command for toggling that setting, if you feel generous.

**Comment by Benature** [comment]
v0.1.3 adds the option in the settings, please have a try! :)
<img width="588" alt="image" src="https://github.com/Benature/obsidian-metadata-hider/assets/35028647/00c2c125-4688-4795-a882-3139d700b80b">
