### ISSUE TITLE
重启obsidian后，开关4会失效

### ISSUE THREAD

**Issue by rain20240327** [Benature/obsidian-metadata-hider#9]
重启obsidian后，开关4会失效

**Comment by rain20240327** [comment]
1.0.0和1.0.0-b2都会失效 （以前应该是正常过一阵的）

**Comment by Benature** [comment]
原本代码是强行等待1s后再隐藏 all properties，在PR #10 后应该会有更快的响应。已在v1.0.1中更新

**Comment by rain20240327** [comment]
木佬！我今天发现
开启了开关4，重启obsidian后，直接点开“所有属性按钮”的话，开关4所隐藏的东西是不生效的，但是……
点开一篇文档后，开关4所隐藏的东西又会生效了。就是这么神奇（√

**Comment by rain20240327** [comment]
> 原本代码是强行等待1s后再隐藏 all properties，在PR #10 后应该会有更快的响应。已在v1.0.1中更新

我回复在上面一楼了，不太会用git  orz

**Comment by rain20240327** [comment]
> 木佬！我今天发现 开启了开关4，重启obsidian后，直接点开“所有属性按钮”的话，开关4所隐藏的东西是不生效的，但是…… 点开一篇文档后，开关4所隐藏的东西又会生效了。就是这么神奇（√

补充下：打开obsidian后，先点开“所有属性按钮”，不可以切换掉“所有属性按钮”页面，在此基础上打开新文档 ， （我的主页中有dv，能查询文档），开关4会生效

**Comment by Benature** [comment]
#11 有更新，尝试下v1.0.2?

**Comment by ghost** [comment]
> #11 有更新，尝试下v1.0.2?

有效！ 哈哈哈  木佬辛苦啦
